### ISSUE TITLE
Shop Menu: TODO List

### ISSUE THREAD

**Issue by madelahn** [CSC207-2022F-UofT/course-project-studyhero#49]
I've finished the basic layout for the buy menu and will finish the layout for the sell menu tonight, I will get started on implementation over the weekend. Here's what I need to get done (this is mostly just a mental note for myself):

- [x] Move different functions (i.e., action listeners) to the correct class for buy menu.
- [x] Get the shop inventory list to be put into the shop buy menu.
- [x] Get the user's inventory list, see how many of each item the user has, also to display for the sell menu.
- [x] Get the user's gold amount.
- [x] Implement purchasing/selling (adding or removing gold from the player).
- [x] Be able to manipulate the user's inventory once an item is purchased/sold.
