### ISSUE TITLE
MILESTONE 5 - Presentation

### ISSUE THREAD

**Issue by madelahn** [CSC207-2022F-UofT/course-project-studyhero#50]
# Milestone 5 Presentation
For the work we need to do for our presentation on Friday, I've compiled a quick list of things we need to get done. I'll make the basic template for it and we can add to it.

### Overview of the Project
- [ ] Our Specification
- [ ] Summary of the Features our team implemented 
- [ ] A brief description of the Overall Design

### Individual Presentation
- [ ] Presenting the feature we implemented
- [ ] Include a demo for each part (pre-recording is a good idea)
- [ ] One challenge we faced during the project *OR* one thing we learned

### Miscellaneous
- [ ] (Time permitting) Highlight future work that can be done on the project
- [ ] Presentation should be 25-30 minutes (around 10-15 slides)
